/*
 * generated by Xtext 2.15.0
 */
package vnf_to_qpn.ui

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
class VnfUiModule extends AbstractVnfUiModule {
}
