/*
 * generated by Xtext 2.15.0
 */
package vnf_to_qpn.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class VnfProposalProvider extends AbstractVnfProposalProvider {
}
