/*
 * generated by Xtext 2.15.0
 */
package vnf_to_qpn


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class VnfStandaloneSetup extends VnfStandaloneSetupGenerated {

	def static void doSetup() {
		new VnfStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
